In [2]:
import pandas as pd

In [232]:
def createDF(sheet, skipRows, skipFooter, header):
    if header:
        df = pd.read_excel (r"./Data/England_2020_April_to_September_Social_Housing_Lettings.xlsx", sheet_name=sheet,  skiprows=skipRows, skipfooter = skipFooter,  header=header)
    else:
        df = pd.read_excel (r"./Data/England_2020_April_to_September_Social_Housing_Lettings.xlsx", sheet_name=sheet,  skiprows=skipRows, skipfooter = skipFooter)
    df.dropna(how='all', inplace=True)
    df.dropna(how='all', axis=1, inplace=True)
    
    if header:
        head = []
        for row in range(len(header)):
            a = df.columns.get_level_values(row).to_series()
            b = a.mask(a.str.startswith('Unnamed')).ffill().fillna('')
            head.append(b)
        df.columns = head
    return df

# Table 1a: New social housing lettings by housing type and provider, 2004/05 to 2020/21 April to September

In [233]:
df1a = createDF(sheet = 'Table 1a', skipRows=4, skipFooter=15, header=[0,1])
display(df1a)

                                                      Total Lettings  \
                                                 Year           Year
0                                            2004/052             ..
1                                            2005/062             ..
2                                            2006/072             ..
3                                             2007/08         366820
4                                             2008/09         379082
5                                            2009/103         367755
6                                             2010/11         393625
7                                             2011/12         394484
8                                             2012/13         378043
9                                             2013/14         396471
10                                            2014/15         385343
11                                            2015/16  374586.300184
12                                            2016/17  334602.035191
13                                            2017/18  312988.656816
14                                            2018/19  313963.936131
15                              2019/20 - Apr to Sept         125149
16                                2019/20 - full year  306187.220716
17                              2020/21 - Apr to Sept          76458
20  % change 19/20 first 6 months to 20/21 first 6...      -0.389064
21                            % change 07/08 to 19/20      -0.165293
22        % lets by provider type 20/21 (Apr to Sept)            NaN
23        % of total new lettings 20/21 (Apr to Sept)            NaN

   All General Needs                               All Supported Housing  \
                 PRP             LA          Total                   PRP
0      143503.000000   18854.000000             ..          76721.000000
1      128239.000000   28123.000000             ..          92406.000000
2      130014.000000   61151.000000             ..          92601.000000
3      127290.000000  124709.000000         251999          94127.000000
4      143086.000000  121704.000000         264790          96468.000000
5      137819.000000  122416.000000         260235          88767.000000
6      151289.000000  117898.000000         269187         108273.000000
7      157535.000000  113143.000000         270678         109671.000000
8      153479.000000  106447.000000         259926         105252.000000
9      170026.000000  112648.000000         282674         100633.000000
10     169547.000000  103980.000000         273527          98726.000000
11     163988.000000  100481.163882  264469.163882          97175.000000
12     146809.000000   91350.839524  238159.839524          84671.000000
13     142234.000000   84788.000000         227022          74929.000000
14     145209.000000   85069.228986  230278.228986          73154.000000
15      67216.000000   24774.000000          91990          30077.000000
16     143786.000000   82488.040754  226274.040754          69678.000000
17      42397.000000   13965.000000          56362          18198.000000
20         -0.369242      -0.436304      -0.387303             -0.394953
21          0.129594      -0.338556      -0.102084             -0.259745
22          0.752227       0.247773            NaN              0.905553
23               NaN            NaN       0.737163                   NaN

                                All  Social Rent Lettings  \
              LA          Total                     Total
0     391.000000             ..                        ..
1    4423.000000             ..                        ..
2   10853.000000             ..                        ..
3   20694.000000         114821                    366820
4   17824.000000         114292                    379082
5   18753.000000         107520                    367755
6   16165.000000         124438                    393625
7   14135.000000         123806                    389805
8   12865.000000         118117                    350135
9   13164.000000         113797                    359077
10  13090.000000         111816                    345279
11  12942.136302  110117.136302             327448.300184
12  11771.195668   96442.195668             290060.035191
13  11038.000000          85967             272805.656816
14  10531.707144   83685.707144             272829.936131
15   3082.000000          33159                    106353
16  10235.179962   79913.179962             264239.220716
17   1898.000000          20096                     65384
20     -0.384166       -0.39395                 -0.385217
21     -0.505404      -0.304019                 -0.279649
22      0.094447            NaN                       NaN
23           NaN       0.262837                  0.855162

   General Needs Social Rent  ... All  Affordable Rent Lettings1  \
                         PRP  ...                          Total
0              143503.000000  ...                             ..
1              128239.000000  ...                             ..
2              130014.000000  ...                             ..
3              127290.000000  ...                             ..
4              143086.000000  ...                             ..
5              137819.000000  ...                             ..
6              151289.000000  ...                             ..
7              152923.000000  ...                             ..
8              126476.000000  ...                          27908
9              134178.000000  ...                          37394
10             131362.000000  ...                          40011
11             124415.000000  ...                          47138
12             110312.000000  ...                          44542
13             108574.000000  ...                          39941
14             111734.000000  ...                          40495
15              51430.000000  ...                          18543
16             108699.000000  ...                          41343
17              32958.000000  ...                          10852
20                 -0.359168  ...                      -0.414766
21                 -0.146052  ...                             ..
22                  0.712513  ...                            NaN
23                       NaN  ...                       0.141934

   General Needs Affordable Rent1                      \
                              PRP        LA     Total
0                              ..        ..        ..
1                              ..        ..        ..
2                              ..        ..        ..
3                              ..        ..        ..
4                              ..        ..        ..
5                              ..        ..        ..
6                              ..        ..        ..
7                              ..        ..        ..
8                           27003       193     27196
9                           35848       702     36550
10                          38185       728     38913
11                          39573      2327     41900
12                          36497      2145     38642
13                          33535      2096     35631
14                          33208      2726     35934
15                          15561      1230     16791
16                          34555      2853     37408
17                           9224       665      9889
20                      -0.407236  -0.45935 -0.411054
21                             ..        ..        ..
22                       0.932754  0.067246       NaN
23                            NaN       NaN       NaN

   Supported Housing Affordable Rent1                      \
                                  PRP        LA     Total
0                                  ..        ..        ..
1                                  ..        ..        ..
2                                  ..        ..        ..
3                                  ..        ..        ..
4                                  ..        ..        ..
5                                  ..        ..        ..
6                                  ..        ..        ..
7                                  ..        ..        ..
8                                 712        ..       712
9                                 844        ..       844
10                               1062        36      1098
11                               5068       170      5238
12                               5512       388      5900
13                               4036       274      4310
14                               4166       395      4561
15                               1614       138      1752
16                               3688       247      3935
17                                916        47       963
20                          -0.432466  -0.65942 -0.450342
21                                 ..        ..        ..
22                           0.951194  0.048806       NaN
23                                NaN       NaN       NaN

   All Rent to Buy lettings Rent to Buy \n(GN & SH)4
                      Total                      PRP        LA
0                        ..                       ..        ..
1                        ..                       ..        ..
2                        ..                       ..        ..
3                        ..                       ..        ..
4                        ..                       ..        ..
5                        ..                       ..        ..
6                        ..                       ..        ..
7                        ..                       ..        ..
8                        ..                       ..        ..
9                        ..                       ..        ..
10                       ..                       ..        ..
11                       ..                       ..        ..
12                       ..                       ..        ..
13                      242                      229        13
14                      639                      362       277
15                      253                      244         9
16                      605                      584        21
17                      222                      220         2
20                 -0.12253                -0.098361 -0.777778
21                       ..                       ..        ..
22                      NaN                 0.990991  0.009009
23                 0.002904                      NaN       NaN

[22 rows x 25 columns]

# Table 1b: New social housing lettings by month of start date, 2018/19 to 2020/21 April to September

In [234]:
df1b = createDF('Table 1b', 4, 13, 0)
df1b.drop(df1b.columns[5], axis=1, inplace=True)

df1b = df1b.rename(columns={ '2019/20 to 2020/21 \n(submitted by 8 Feb)':  'percentage change 2019/20 to 2020/21 \n(submitted by 8 Feb)',
                        '2018/19 to 2019/20 (submitted by year end)': 'percentage change 2018/19 to 2019/20 (submitted by year end)'})
display(df1b)

,Month\n(Count of new lettings),2020/21\n(submitted by 8 Feb)1,2019/20\n(submitted by 8 Feb)1,2019/20\n(submitted by year end)2,2018/19\n(submitted by year end)2,percentage change 2019/20 to 2020/21 \n(submitted by 8 Feb),percentage change 2018/19 to 2019/20 (submitted by year end)
0,April,5468.0,22829.0,28853.722869,28474.368492,-0.760480,0.013323
1,May,7435.0,20508.0,25917.158652,26729.741758,-0.637459,-0.030400
2,June,15210.0,19809.0,25354.452989,26653.002259,-0.232167,-0.048721
3,July,16897.0,22932.0,29584.368267,29431.725504,-0.263169,0.005186
4,August,16111.0,18847.0,25045.251002,25723.413776,-0.145169,-0.026364
5,September,15337.0,20224.0,27268.399744,24563.785600,-0.241644,0.110106
6,October,NaN,NaN,26984.234822,29446.837469,NaN,-0.083629
7,November,NaN,NaN,25337.165545,26470.483918,NaN,-0.042814
8,December,NaN,NaN,23559.696240,23160.217538,NaN,0.017248
9,January,NaN,NaN,23530.800724,23921.173631,NaN,-0.016319
10,February,NaN,NaN,24152.219643,24232.401385,NaN,-0.003309
11,March,NaN,NaN,20599.750217,26078.785424,NaN,-0.210095
12,April to September,76458.0,125149.0,162023.353523,161576.037390,-0.389064,0.002768
13,October to March,NaN,NaN,144163.867193,153309.899367,NaN,-0.059657
14,Full year - April to March,NaN,NaN,306187.220716,314885.936757,NaN,-0.027625
16,% of new lets starting in first 6 months,NaN,NaN,0.529164,0.513126,NaN,NaN
17,% of new lets starting in second 6 months,NaN,NaN,0.470836,0.486874,NaN,NaN

# Table 1c: Social housing providers and their new lettings from 2004/05 to 2020/21 April to September

In [44]:
df1c = createDF(sheet='Table 1c', skipRows=4, skipFooter=14, header=[0,1])
df1c = df1c.rename(columns={ 'Year3': 'Year'})
display(df1c)

                                                       \
                                                 Year
0                                            2004/051
1                                            2005/061
2                                            2006/071
3                                             2007/08
4                                             2008/09
5                                            2009/102
6                                             2010/11
7                                             2011/12
8                                             2012/13
9                                             2013/14
10                                            2014/15
11                                            2015/16
12                                            2016/17
13                                            2017/18
14                                            2018/19
15                              2019/20 - Apr to Sept
16                                2019/20 - full year
17                              2020/21 - Apr to Sept
20  % change 19/20 first 6 months to 20/21 first 6...
21                            % change 07/08 to 19/20
22      % lets by provider type 20/21 \n(Apr to Sept)

   Social Rent and Affordable Rent lettings                                \
                                        PRP             LA          Total
0                             220224.000000   19245.000000             ..
1                             220645.000000   32546.000000             ..
2                             222615.000000   72004.000000             ..
3                             221417.000000  145403.000000         366820
4                             239554.000000  139528.000000         379082
5                             226586.000000  141169.000000         367755
6                             259562.000000  134063.000000         393625
7                             267206.000000  127278.000000         394484
8                             258731.000000  119312.000000         378043
9                             270659.000000  125812.000000         396471
10                            268273.000000  117070.000000         385343
11                            261163.000000  113423.300184  374586.300184
12                            231480.000000  103122.035191  334602.035191
13                            216934.000000   95812.656816  312746.656816
14                            218001.000000   95324.000000         313325
15                             97049.000000   27847.000000         124896
16                            212880.000000   92702.220716  305582.220716
17                             60375.000000   15861.000000          76236
20                                -0.377892      -0.430423      -0.389604
21                                -0.038556      -0.362446      -0.166942
22                                 0.791949       0.208051            NaN

   Number of providers                     Average lettings per provider  \
                   PRP        LA     Total                           PRP
0           716.000000        ..        ..                    307.575419
1           690.000000        ..        ..                    319.775362
2           703.000000        ..        ..                    316.664296
3           688.000000       205       893                    321.827035
4           685.000000       187       872                    349.713869
5           644.000000       177       821                    351.841615
6           675.000000       174       849                    384.536296
7           659.000000       171       830                    405.471927
8           626.000000       168       794                    413.308307
9           616.000000       170       786                    439.381494
10          621.000000       172       793                    432.001610
11          638.000000       171       809                    409.346395
12          632.000000       171       803                    366.265823
13          548.000000       168       716                    395.864964
14          499.000000       166       665                    436.875752
15          429.000000       143       572                    226.221445
16          469.000000       159       628                    453.901919
17          387.000000       127       514                    156.007752
20           -0.097902 -0.111888 -0.101399                     -0.310376
21           -0.318314  -0.22439 -0.296753                      0.410391
22            0.752918  0.247082       NaN                           NaN


            LA       Total
0           ..          ..
1           ..          ..
2           ..          ..
3   709.282927  410.772676
4   746.139037  434.727064
5   797.564972  447.935445
6   770.477011  463.633687
7   744.315789  475.281928
8   710.190476  476.124685
9   740.070588  504.416031
10         681  485.863808
11  663.444444  463.055624
12  603.052837  416.689957
13  570.313433  436.797007
14  574.240964  471.165414
15  194.734266   218.34965
16  583.032835  486.595893
17  124.889764  148.319066
20   -0.358666   -0.320727
21   -0.177997    0.184587
22         NaN         NaN

# Table 1d: Reported new social housing lettings by local authority area location of property, 2019/20 to 2020/21 April to September

In [42]:
df1d = createDF(sheet='Table 1d', skipRows=5, skipFooter=10, header=[0,1])
display(df1d)

    LA Code \n(ONS eCode)       LA Name 2020/21 April to September  \
                                                   Total Lettings1
0               E07000223          Adur                       11.0
1               E07000026     Allerdale                      303.0
2               E07000032  Amber Valley                      248.0
3               E07000224          Arun                      122.0
4               E07000170      Ashfield                      168.0
..                    ...           ...                        ...
315             E07000128          Wyre                       96.0
316             E07000239   Wyre Forest                      108.0
317             E06000014          York                      173.0
318                   NaN       Missing                       95.0
319                 Total           NaN                    76234.0

                                                                     \
    General Needs Social Rent PRP Supported Housing Social Rent PRP
0                             3.0                               7.0
1                           251.0                              32.0
2                           118.0                              98.0
3                            45.0                              21.0
4                            23.0                               8.0
..                            ...                               ...
315                          34.0                              55.0
316                          45.0                              38.0
317                          50.0                              16.0
318                           0.0                              88.0
319                       32956.0                           17277.0

                                                                             \
    General Needs Affordable Rent PRP Supported Housing Affordable Rent PRP
0                                 0.0                                   1.0
1                                20.0                                   0.0
2                                32.0                                   0.0
3                                 5.0                                   0.0
4                                 4.0                                   0.0
..                                ...                                   ...
315                               7.0                                   0.0
316                              23.0                                   2.0
317                              13.0                                   2.0
318                               0.0                                   2.0
319                            9224.0                                 916.0

                                                                   \
    General Needs Social Rent LA Supported Housing Social Rent LA
0                            0.0                              0.0
1                            0.0                              0.0
2                            0.0                              0.0
3                           41.0                              0.0
4                          124.0                              9.0
..                           ...                              ...
315                          0.0                              0.0
316                          0.0                              0.0
317                         82.0                              9.0
318                          0.0                              5.0
319                      13298.0                           1851.0

                                                                               \
    General Needs Affordable Rent \nLA Supported Housing Affordable Rent \nLA
0                                  0.0                                    0.0
1                                  0.0                                    0.0
2                                  0.0                                    0.0
3                                 10.0                                    0.0
4                                  0.0                                    0.0
..                                 ...                                    ...
315                                0.0                                    0.0
316                                0.0                                    0.0
317                                1.0                                    0.0
318                                0.0                                    0.0
319                              665.0                                   47.0

    2019/20 April to September                                \
               Total Lettings1 General Needs Social Rent PRP
0                         90.0                          17.0
1                        448.0                         390.0
2                        312.0                         167.0
3                        206.0                          42.0
4                        271.0                          37.0
..                         ...                           ...
315                      185.0                          70.0
316                      237.0                         114.0
317                      281.0                          59.0
318                        NaN                           NaN
319                   124896.0                       51430.0

                                                                         \
    Supported Housing Social Rent PRP General Needs Affordable Rent PRP
0                                17.0                               1.0
1                                34.0                              17.0
2                               113.0                              32.0
3                                19.0                              41.0
4                                17.0                               2.0
..                                ...                               ...
315                              70.0                              41.0
316                             105.0                              15.0
317                              41.0                              30.0
318                               NaN                               NaN
319                           28444.0                           15561.0

                                                                        \
    Supported Housing Affordable Rent PRP General Needs Social Rent LA
0                                     0.0                         55.0
1                                     7.0                          0.0
2                                     0.0                          0.0
3                                     3.0                        101.0
4                                     1.0                        190.0
..                                    ...                          ...
315                                   4.0                          0.0
316                                   3.0                          0.0
317                                  18.0                        118.0
318                                   NaN                          NaN
319                                1614.0                      23538.0

                                                                         \
    Supported Housing Social Rent LA General Needs Affordable Rent \nLA
0                                0.0                                0.0
1                                0.0                                0.0
2                                0.0                                0.0
3                                0.0                                0.0
4                               24.0                                0.0
..                               ...                                ...
315                              0.0                                0.0
316                              0.0                                0.0
317                             11.0                                1.0
318                              NaN                                NaN
319                           2941.0                             1230.0


    Supported Housing Affordable Rent \nLA
0                                      0.0
1                                      0.0
2                                      0.0
3                                      0.0
4                                      0.0
..                                     ...
315                                    0.0
316                                    0.0
317                                    3.0
318                                    NaN
319                                  138.0

[320 rows x 20 columns]

# Table 1e: Length of time new social housing households were on the waiting list in the local authority area of their new letting, England, 2019/20 to 2020/21 April to September

In [41]:
df1e = createDF(sheet='Table 1e', skipRows=4, skipFooter=8, header=[0,2])
display(df1e)

    2020/21 April to September  Total Lettings                     Needs Type  \
                                         Count  Percentage (%)  General Needs
1             Less than 1 year           29286        0.603698          22825
2     1 year but under 2 years            7339        0.151285           6227
3    2 years but under 3 years            3108        0.064068           2680
4    3 years but under 4 years            1419        0.029251           1255
5    4 years but under 5 years            1223        0.025211            812
6              5 years or more            6136        0.126487           4586
7                  Known total           48511               1            NaN
8                   Don't know           27947             NaN          17977
13  2019/20 April to September  Total Lettings             NaN     Needs Type
15                         NaN           Count  Percentage (%)  General Needs
17            Less than 1 year           46119        0.593705          35155
18    1 year but under 2 years           10977        0.141311           9310
19   2 years but under 3 years            4778        0.061509           4185
20   3 years but under 4 years            2121        0.027304           1834
21   4 years but under 5 years            3024        0.038929           1764
22             5 years or more           10661        0.137243           8095
23                 Known total           77680               1            NaN
24                  Don't know           47468             NaN          31646

                         Rent Type                     Provider Type  \
    Supported Housing  Social Rent  Affordable Rent  Local Authority
1                6461        25510             3752             6974
2                1112         6232             1104             1911
3                 428         2597              506              838
4                 164         1177              241              347
5                 411         1082              139              220
6                1550         5152              954             1638
7                 NaN          NaN              NaN              NaN
8                9970        23634             4156             3935
13                NaN    Rent Type              NaN    Provider Type
15  Supported Housing  Social Rent  Affordable Rent  Local Authority
17              10964        40284             5813            12086
18               1667         9305             1667             2996
19                593         3995              783             1386
20                287         1775              344              678
21               1260         2530              491              583
22               2566         8959             1685             3016
23                NaN          NaN              NaN              NaN
24              15822        39505             7759             7111


    Private Registered Provider (PRP)
1                               22312
2                                5428
3                                2270
4                                1072
5                                1003
6                                4498
7                                 NaN
8                               24012
13                                NaN
15  Private Registered Provider (PRP)
17                              34033
18                               7981
19                               3392
20                               1443
21                               2441
22                               7645
23                                NaN
24                              40357

# Table 2a: New social housing lettings by tenancy type, 2019/20 to 2020/21 April to September

In [243]:
df2a1 = createDF(sheet='Table 2a', skipRows=4, skipFooter=30, header=[0,1,2])

# display(df2a1)

In [244]:
df2a2 = createDF(sheet='Table 2a', skipRows=18, skipFooter=16, header=[0,1,2])

# display(df2a2)

In [319]:
df2a = pd.concat([df2a1, df2a2], axis=1)
display(df2a)

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,Secure1,44.000000,0.000941,13094.000000,0.900898,14.000000,0.001439,1573.000000,0.860369,37.00000,...,2535.000000,0.861952,21.000000,0.001350,1108.000000,0.900813,1.000000,0.000620,133.000000,0.963768
1,Secure Flexible1,2.000000,0.000030,537.000000,0.063762,0.000000,0.000000,13.000000,0.013880,2.00000,...,29.000000,0.009861,0.000000,0.000000,117.000000,0.095122,0.000000,0.000000,4.000000,0.028986
2,Assured2,33270.000000,0.751907,160.000000,0.023159,6179.000000,0.350953,0.000000,0.000000,26938.00000,...,0.000000,0.000000,9677.000000,0.621875,0.000000,0.000000,644.000000,0.399009,0.000000,0.000000
3,Assured Shorthold3,8254.000000,0.232529,64.000000,0.003835,1964.000000,0.128689,1.000000,0.000270,5505.00000,...,0.000000,0.000000,5666.000000,0.364115,0.000000,0.000000,263.000000,0.162949,0.000000,0.000000
4,Licence Agreement4,57.000000,0.000943,0.000000,0.000000,9804.000000,0.510654,304.000000,0.113222,55.00000,...,372.000000,0.126488,3.000000,0.000193,0.000000,0.000000,695.000000,0.430607,1.000000,0.007246
5,Other,555.000000,0.013651,108.000000,0.008346,232.000000,0.008265,7.000000,0.012259,421.00000,...,5.000000,0.001700,194.000000,0.012467,5.000000,0.004065,11.000000,0.006815,0.000000,0.000000
6,Total,42182.000000,1.000000,13963.000000,1.000000,18193.000000,1.000000,1898.000000,1.000000,32958.00000,...,2941.000000,1.000000,15561.000000,1.000000,1230.000000,1.000000,1614.000000,1.000000,138.000000,1.000000
8,% offered on starter/ introductory period5,0.671141,NaN,0.657006,NaN,0.230985,NaN,0.553077,NaN,0.68736,...,0.485889,NaN,0.681126,NaN,0.707317,NaN,0.315985,NaN,0.543478,NaN

# Table 2b: Average re-let time for new lettings, 2019/20 to 2020/21 April to September

In [246]:
df2b = createDF(sheet='Table 2b', skipRows=5, skipFooter=7, header=[0,1])
display(df2b)

                               General Needs Social Rent             \
                          Year                       PRP         LA
0    2019/20 Apr to Sep - Mean                 31.488139  44.895573
1  2019/20 Apr to Sep - Median                 20.000000  29.000000
2    2020/21 Apr to Sep - Mean                 53.412950  68.852008
3  2020/21 Apr to Sep - Median                 35.000000  49.000000

             Supported Housing Social Rent                        \
       Total                           PRP         LA      Total
0  35.697724                     35.797602  42.336280  36.410323
1  22.000000                      8.000000  28.000000   9.000000
2  57.851479                     47.224460  71.627229  49.585895
3  37.000000                     14.000000  46.000000  17.000000

  General Needs Affordable Rent                        \
                            PRP         LA      Total
0                     20.444730  34.685366  21.487969
1                      7.000000  17.000000   8.000000
2                     38.129553  56.215038  39.345738
3                     14.000000  28.000000  14.000000

  Supported Housing Affordable Rent
                                PRP         LA      Total
0                         56.016109  30.144928  53.978311
1                         11.000000  21.000000  13.000000
2                         65.239083  82.744681  66.093458
3                         19.000000  42.000000  13.000000

# Table 2ci: Average (mean) re-let time for new lettings by month of start date, 2018/19 to 2020/21 April to September

In [251]:
df2ci1 = createDF(sheet='Table 2ci', skipRows=4, skipFooter=32, header=[0,1,2])
# display(df2ci1)

In [250]:
df2ci2 = createDF(sheet='Table 2ci', skipRows=24, skipFooter=13, header=[0,1,2])
# display(df2ci2)

In [252]:
df2ci = pd.concat([df2ci1, df2ci2], axis=1)
display(df2ci)

                                   2020/21 (submitted by 8 Feb)1  \
                                                  Total Lettings
   Month\n(Count of new lettings) Month\n(Count of new lettings)
0                           April                           48.0
1                             May                           50.0
2                            June                           62.0
3                           July                            54.0
4                          August                           52.0
5                       September                           49.0
6                         October                            NaN
7                        November                            NaN
8                        December                            NaN
9                         January                            NaN
10                       February                            NaN
11                          March                            NaN
12             April to September                           54.0
13               October to March                            NaN
14     Full year - April to March                            NaN

                                                    \
   General Needs Social Rent
                         PRP         LA      Total
0                  47.136752  50.996491  48.597610
1                  53.794788  59.292202  55.206646
2                  62.800056  77.353414  66.572083
3                  54.145087  70.787664  58.922883
4                  50.210564  72.207640  56.953663
5                  47.130120  64.945210  52.288055
6                        NaN        NaN        NaN
7                        NaN        NaN        NaN
8                        NaN        NaN        NaN
9                        NaN        NaN        NaN
10                       NaN        NaN        NaN
11                       NaN        NaN        NaN
12                 53.412950  68.852008  57.851479
13                       NaN        NaN        NaN
14                       NaN        NaN        NaN

                                                        \
   Supported Housing Social Rent
                             PRP         LA      Total
0                      48.459030  47.666667  48.438269
1                      38.850363  42.791304  39.088143
2                      48.340663  89.061404  52.563372
3                      48.832028  71.507338  51.588430
4                      46.865089  75.682540  50.191049
5                      48.560923  64.807317  50.380874
6                            NaN        NaN        NaN
7                            NaN        NaN        NaN
8                            NaN        NaN        NaN
9                            NaN        NaN        NaN
10                           NaN        NaN        NaN
11                           NaN        NaN        NaN
12                     47.224460  71.627229  49.585895
13                           NaN        NaN        NaN
14                           NaN        NaN        NaN

                                             ...  \
   General Needs Affordable Rent             ...
                             PRP         LA  ...
0                      32.638095  44.535714  ...
1                      44.603681  58.760000  ...
2                      52.397397  66.382114  ...
3                      37.604450  60.344633  ...
4                      30.284222  43.200000  ...
5                      29.808475  56.489796  ...
6                            NaN        NaN  ...
7                            NaN        NaN  ...
8                            NaN        NaN  ...
9                            NaN        NaN  ...
10                           NaN        NaN  ...
11                           NaN        NaN  ...
12                     38.129553  56.215038  ...
13                           NaN        NaN  ...
14                           NaN        NaN  ...

   2018/19 to 2019/20 (submitted by year end)2                                \
                     General Needs Social Rent Supported Housing Social Rent
                                         Total                           PRP
0                                    -0.094786                     -0.026149
1                                     0.046910                     -0.083544
2                                     0.057454                      0.040753
3                                     0.015710                     -0.209157
4                                     0.074839                      0.023894
5                                     0.051194                     -0.183309
6                                     0.023611                     -0.074830
7                                    -0.004856                      0.491015
8                                     0.042543                     -0.090653
9                                     0.080183                      0.030041
10                                    0.138531                     -0.109846
11                                    0.099663                     -0.130416
12                                    0.170697                     -0.057566
13                                    0.084651                      0.020389
14                                    0.052477                     -0.032383

                                                                          \
                       General Needs Affordable Rent
          LA     Total                           PRP        LA     Total
0   0.044410 -0.018044                     -0.252052 -0.034965 -0.234195
1   0.010189 -0.065305                      0.167651 -0.615208 -0.051302
2  -0.162722  0.007389                      0.068888 -0.204651  0.034205
3  -0.075828 -0.190876                      0.008928  0.018430  0.022701
4  -0.197244 -0.013218                      0.131798 -0.062041  0.118143
5  -0.069864 -0.164750                     -0.018909 -0.275284 -0.041315
6  -0.078460 -0.075993                      0.003068 -0.255782 -0.035165
7  -0.080650  0.357232                      0.015680  0.113104  0.029900
8  -0.104621 -0.094597                      0.060641 -0.324251  0.012216
9  -0.206010 -0.009814                      0.298975 -0.504536  0.103080
10  0.006230 -0.081700                      0.093157 -0.492099 -0.060420
11  0.015568 -0.093870                      0.038733 -0.580169 -0.092611
12  0.109719 -0.026230                      0.029179 -0.009032  0.028003
13 -0.052045  0.010684                      0.087083 -0.366849  0.005000
14 -0.064527 -0.036912                      0.043830 -0.316865 -0.016118


   Supported Housing Affordable Rent
                                 PRP        LA     Total
0                           0.465149 -0.258920  0.490745
1                           0.520448  0.556300  0.512715
2                           0.359979  0.110583  0.349867
3                           0.417384 -0.444306  0.362064
4                           0.790107 -0.076580  0.707913
5                           1.555027 -0.158510  1.393979
6                           0.656677 -0.099152  0.614834
7                           0.444813  0.192360  0.503411
8                           0.469862 -0.487467  0.397483
9                           0.565678  0.513158  0.568401
10                         -0.034695  0.028256 -0.027628
11                          0.336847 -0.446267  0.305612
12                          0.150807  0.810554  0.230690
13                          0.293577 -0.051824  0.305417
14                          0.447373 -0.068798  0.436441

[15 rows x 80 columns]

# Table 2cii: Average (median) re-let time for new lettings by month of start date, 2018/19 to 2020/21 April to September

In [256]:
df2cii1 = createDF(sheet='Table 2cii', skipRows=4, skipFooter=32, header=[0,1,2])
# display(df2cii1)

In [276]:
df2cii2 = createDF(sheet='Table 2cii', skipRows=24, skipFooter=13, header=[0,1,2])
# display(df2cii2)

In [275]:
df2cii = pd.concat([df2cii1, df2cii2], axis=1)
display(df2cii)

                                   2020/21 (submitted by 8 Feb)1  \
                                                  Total Lettings
   Month\n(Count of new lettings) Month\n(Count of new lettings)
0                           April                           24.0
1                             May                           39.0
2                            June                           45.0
3                           July                            28.0
4                          August                           27.0
5                       September                           26.0
6                         October                            NaN
7                        November                            NaN
8                        December                            NaN
9                         January                            NaN
10                       February                            NaN
11                          March                            NaN
12             April to September                           29.0
13               October to March                            NaN
14     Full year - April to March                            NaN

                                                                              \
   General Needs Social Rent             Supported Housing Social Rent
                         PRP    LA Total                           PRP    LA
0                       26.0  35.0  30.0                          21.0  20.0
1                       50.0  49.0  50.0                           8.0  24.0
2                       56.0  70.0  58.0                          13.0  63.0
3                       31.0  50.0  36.0                          14.0  50.0
4                       29.0  42.0  32.0                          15.0  47.0
5                       29.0  42.0  32.0                          14.0  42.0
6                        NaN   NaN   NaN                           NaN   NaN
7                        NaN   NaN   NaN                           NaN   NaN
8                        NaN   NaN   NaN                           NaN   NaN
9                        NaN   NaN   NaN                           NaN   NaN
10                       NaN   NaN   NaN                           NaN   NaN
11                       NaN   NaN   NaN                           NaN   NaN
12                      35.0  49.0  37.0                          14.0  46.0
13                       NaN   NaN   NaN                           NaN   NaN
14                       NaN   NaN   NaN                           NaN   NaN

                                              ...  \
         General Needs Affordable Rent        ...
   Total                           PRP    LA  ...
0   21.0                          11.0  14.5  ...
1    9.0                          40.0  43.5  ...
2   17.0                          31.0  46.0  ...
3   17.0                           8.0  35.0  ...
4   19.0                           8.0  28.0  ...
5   17.0                          11.0   8.0  ...
6    NaN                           NaN   NaN  ...
7    NaN                           NaN   NaN  ...
8    NaN                           NaN   NaN  ...
9    NaN                           NaN   NaN  ...
10   NaN                           NaN   NaN  ...
11   NaN                           NaN   NaN  ...
12  17.0                          14.0  28.0  ...
13   NaN                           NaN   NaN  ...
14   NaN                           NaN   NaN  ...

   2018/19 to 2019/20 (submitted by year end)2                                \
                     General Needs Social Rent Supported Housing Social Rent
                                         Total                           PRP
0                                    -0.125000                      0.000000
1                                     0.086957                      0.000000
2                                     0.045455                      0.000000
3                                     0.045455                     -0.125000
4                                     0.000000                      0.000000
5                                     0.090909                      0.142857
6                                     0.000000                      0.000000
7                                     0.000000                      0.142857
8                                     0.000000                      0.142857
9                                     0.000000                      0.000000
10                                    0.071429                      0.000000
11                                    0.136364                      0.142857
12                                    0.095238                      0.125000
13                                    0.090909                      0.142857
14                                    0.045455                      0.142857

                                                                          \
                       General Needs Affordable Rent
          LA     Total                           PRP        LA     Total
0   0.000000  0.000000                     -0.714286  0.034483 -0.571429
1   0.000000  0.000000                      0.428571 -0.136364  0.250000
2   0.250000 -0.111111                      0.142857 -0.190476  0.000000
3  -0.034483 -0.100000                      0.142857  0.500000  0.142857
4  -0.071429  0.000000                      0.428571  0.047619  0.375000
5   0.035714  0.125000                     -0.100000 -0.333333 -0.181818
6   0.035714  0.000000                      0.000000 -0.052632  0.000000
7   0.000000  0.111111                      0.000000  0.071429  0.000000
8   0.000000  0.125000                      0.333333 -0.285714  0.333333
9   0.000000  0.000000                      0.166667 -0.100000  0.166667
10  0.029412  0.000000                      0.071429 -0.400000  0.000000
11 -0.034483  0.100000                     -0.125000 -0.708333 -0.222222
12  0.000000  0.100000                      0.400000 -0.333333  0.400000
13  0.035714  0.000000                      0.142857 -0.333333  0.142857
14  0.035714  0.000000                      0.000000 -0.285714  0.000000


   Supported Housing Affordable Rent
                                 PRP         LA     Total
0                          -0.285714   8.000000 -0.166667
1                           0.071429   0.000000  0.071429
2                          -0.230769   0.766667 -0.285714
3                          -0.117647  -0.285714  0.000000
4                           0.000000   0.000000  0.000000
5                          -0.153846   1.000000  0.076923
6                          -0.076923   0.400000 -0.071429
7                          -0.214286   0.105263 -0.172414
8                          -0.076923  -0.285714 -0.034483
9                           0.000000   1.000000  0.000000
10                         -0.375000   3.000000 -0.266667
11                         -0.312500   1.187500 -0.312500
12                          1.428571  24.000000  1.571429
13                         -0.107143   1.100000  0.000000
14                         -0.142857   0.500000 -0.071429

[15 rows x 80 columns]

# Table 2d: Reason the property was vacant prior to the new letting, 2019/20 to 2020/21 April to September

In [279]:
df2d1 = createDF(sheet='Table 2d', skipRows=4, skipFooter=38, header=[0,1])
# display(df2d1)

                          2020/21 April to September  \
                                       % of lettings
0                           First let of a property1
1  Relet - internal transfer (no renewal of fixed...
2              Relet - Renewal of fixed term tenancy
3  Relet - previous tenant moved to other social ...
4                       Relet - previous tenant died
5      Relet - property abandoned by previous tenant
6                    Relet - previous tenant evicted
7  Relet - previous tenant moved to private secto...
8  Relet - tenant occupied same property as tempo...

  General Needs Social Rent                     General Needs Affordable Rent  \
                        PRP       LA2     Total                           PRP
0                  0.046362  0.027222  0.040860                      0.445252
1                  0.107258  0.190254  0.131118                      0.062229
2                  0.024819  0.010678  0.020754                      0.065590
3                  0.156684  0.117461  0.145408                      0.107329
4                  0.196037  0.248609  0.211151                      0.045533
5                  0.035075  0.031508  0.034050                      0.018105
6                  0.031282  0.040081  0.033812                      0.017671
7                  0.398689  0.329298  0.378740                      0.237424
8                  0.003793  0.004888  0.004108                      0.000867

                      Supported Housing Social Rent                      \
         LA     Total                           PRP       LA2     Total
0  0.416541  0.443321                      0.032529  0.004862  0.029852
1  0.118797  0.066033                      0.111420  0.094543  0.109787
2  0.004511  0.061482                      0.002257  0.000540  0.002091
3  0.066165  0.104561                      0.219309  0.126418  0.210320
4  0.129323  0.051168                      0.184060  0.436521  0.208490
5  0.016541  0.018000                      0.039706  0.015667  0.037380
6  0.010526  0.017191                      0.066505  0.018368  0.061847
7  0.234586  0.237233                      0.336690  0.296056  0.332758
8  0.003008  0.001011                      0.007524  0.007023  0.007476

  Supported Housing Affordable Rent
                                PRP        LA     Total
0                          0.087336  0.106383  0.088266
1                          0.093886  0.085106  0.093458
2                          0.001092  0.000000  0.001038
3                          0.266376  0.085106  0.257529
4                          0.205240  0.361702  0.212876
5                          0.026201  0.000000  0.024922
6                          0.050218  0.000000  0.047767
7                          0.265284  0.361702  0.269990
8                          0.004367  0.000000  0.004154

In [278]:
df2d2 = createDF(sheet='Table 2d', skipRows=18, skipFooter=24, header=[0,1])
# display(df2d2)

                          2019/20 April to September  \
                                       % of lettings
0                           First let of a property1
1  Relet - internal transfer (no renewal of fixed...
2              Relet - Renewal of fixed term tenancy
3  Relet - previous tenant moved to other social ...
4                       Relet - previous tenant died
5      Relet - property abandoned by previous tenant
6                    Relet - previous tenant evicted
7  Relet - previous tenant moved to private secto...
8  Relet - tenant occupied same property as tempo...

  General Needs Social Rent                     General Needs Affordable Rent  \
                        PRP       LA2     Total                           PRP
0                  0.069415  0.032628  0.057865                      0.439046
1                  0.130624  0.212592  0.156360                      0.087462
2                  0.023858  0.009899  0.019475                      0.072103
3                  0.146179  0.116025  0.136712                      0.093567
4                  0.144040  0.197468  0.160815                      0.034766
5                  0.035446  0.031608  0.034241                      0.017351
6                  0.067081  0.059903  0.064828                      0.042092
7                  0.376240  0.334905  0.363262                      0.206606
8                  0.007116  0.004971  0.006443                      0.007005


         LA     Total
0  0.378862  0.434638
1  0.116260  0.089572
2  0.000813  0.066881
3  0.060163  0.091120
4  0.099187  0.039485
5  0.017886  0.017390
6  0.041463  0.042046
7  0.281301  0.212078
8  0.004065  0.006789

In [282]:
df2d = pd.concat([df2d1, df2d2], axis=1)
display(df2d)

                          2020/21 April to September  \
                                       % of lettings
0                           First let of a property1
1  Relet - internal transfer (no renewal of fixed...
2              Relet - Renewal of fixed term tenancy
3  Relet - previous tenant moved to other social ...
4                       Relet - previous tenant died
5      Relet - property abandoned by previous tenant
6                    Relet - previous tenant evicted
7  Relet - previous tenant moved to private secto...
8  Relet - tenant occupied same property as tempo...

  General Needs Social Rent                     General Needs Affordable Rent  \
                        PRP       LA2     Total                           PRP
0                  0.046362  0.027222  0.040860                      0.445252
1                  0.107258  0.190254  0.131118                      0.062229
2                  0.024819  0.010678  0.020754                      0.065590
3                  0.156684  0.117461  0.145408                      0.107329
4                  0.196037  0.248609  0.211151                      0.045533
5                  0.035075  0.031508  0.034050                      0.018105
6                  0.031282  0.040081  0.033812                      0.017671
7                  0.398689  0.329298  0.378740                      0.237424
8                  0.003793  0.004888  0.004108                      0.000867

                      Supported Housing Social Rent                      \
         LA     Total                           PRP       LA2     Total
0  0.416541  0.443321                      0.032529  0.004862  0.029852
1  0.118797  0.066033                      0.111420  0.094543  0.109787
2  0.004511  0.061482                      0.002257  0.000540  0.002091
3  0.066165  0.104561                      0.219309  0.126418  0.210320
4  0.129323  0.051168                      0.184060  0.436521  0.208490
5  0.016541  0.018000                      0.039706  0.015667  0.037380
6  0.010526  0.017191                      0.066505  0.018368  0.061847
7  0.234586  0.237233                      0.336690  0.296056  0.332758
8  0.003008  0.001011                      0.007524  0.007023  0.007476

  Supported Housing Affordable Rent                      \
                                PRP        LA     Total
0                          0.087336  0.106383  0.088266
1                          0.093886  0.085106  0.093458
2                          0.001092  0.000000  0.001038
3                          0.266376  0.085106  0.257529
4                          0.205240  0.361702  0.212876
5                          0.026201  0.000000  0.024922
6                          0.050218  0.000000  0.047767
7                          0.265284  0.361702  0.269990
8                          0.004367  0.000000  0.004154

                          2019/20 April to September  \
                                       % of lettings
0                           First let of a property1
1  Relet - internal transfer (no renewal of fixed...
2              Relet - Renewal of fixed term tenancy
3  Relet - previous tenant moved to other social ...
4                       Relet - previous tenant died
5      Relet - property abandoned by previous tenant
6                    Relet - previous tenant evicted
7  Relet - previous tenant moved to private secto...
8  Relet - tenant occupied same property as tempo...

  General Needs Social Rent                     General Needs Affordable Rent  \
                        PRP       LA2     Total                           PRP
0                  0.069415  0.032628  0.057865                      0.439046
1                  0.130624  0.212592  0.156360                      0.087462
2                  0.023858  0.009899  0.019475                      0.072103
3                  0.146179  0.116025  0.136712                      0.093567
4                  0.144040  0.197468  0.160815                      0.034766
5                  0.035446  0.031608  0.034241                      0.017351
6                  0.067081  0.059903  0.064828                      0.042092
7                  0.376240  0.334905  0.363262                      0.206606
8                  0.007116  0.004971  0.006443                      0.007005


         LA     Total
0  0.378862  0.434638
1  0.116260  0.089572
2  0.000813  0.066881
3  0.060163  0.091120
4  0.099187  0.039485
5  0.017886  0.017390
6  0.041463  0.042046
7  0.281301  0.212078
8  0.004065  0.006789

In [167]:
df2d3 = createDF(sheet='Table 2d', skipRows=30, skipFooter=12, header=[0,1])
display(df2d3)

                          Supported Housing Social Rent                      \
            % of lettings                           PRP       LA2     Total
0  First Let of Property1                      0.043313  0.070724  0.045882
1                   Relet                      0.956687  0.929276  0.954118

  Supported Housing Affordable Rent
                                PRP       LA     Total
0                          0.223048  0.15942  0.218037
1                          0.776952  0.84058  0.781963

# Table 3a: Household composition by type of letting, for new social housing lettings, 2019/20 to 2020/21 April to September

In [310]:
df3a1a = createDF(sheet='Table 3a', skipRows=4, skipFooter=59, header=[0,1])
# display(df3a1a)

In [309]:
df3a1b = createDF(sheet='Table 3a', skipRows=18, skipFooter=46, header=[0,1])
# display(df3a1b)

In [323]:
df3a1 = pd.merge(df3a1a, df3a1b, how="inner", left_index=True, right_index=True)
display(df3a1)

       2020/21 April to September All Lettings General Needs Social Rent  \
                                                                     PRP
0                   Single female        12114                      5029
1   Single female with child(ren)        15040                      7636
2                     Single male        17638                      6677
3     Single male with child(ren)         1292                       702
4                         Couple3         2333                      1298
5         Couple with child(ren)3         6866                      3564
6                   Single elder1         9255                      2780
7                   Elder couple1         2113                       865
8                          Other5         5089                      2671
9                           Total        71740                     31222
10                       Refused4         4496                      1736

                 Supported Housing Social Rent               \
      LA2  Total                           PRP   LA2  Total
0    1921   6950                          3654   180   3834
1    3256  10892                           810    58    868
2    2758   9435                          6404   282   6686
3     309   1011                            28     8     36
4     493   1791                           129    23    152
5    1668   5232                            84    12     96
6    1254   4034                          3495  1022   4517
7     381   1246                           463   179    642
8    1136   3807                           362    54    416
9   13176  44398                         15429  1818  17247
10    122   1858                          1848    33   1881

   General Needs Affordable Rent       ... General Needs Social Rent  \
                             PRP   LA  ...                     Total
0                           1071   78  ...                     11717
1                           3061  158  ...                     17029
2                           1156  105  ...                     14838
3                            227   16  ...                      1488
4                            353   28  ...                      3340
5                           1439   98  ...                      9327
6                            358   72  ...                      6314
7                            161   15  ...                      1964
8                            761   86  ...                      5881
9                           8587  656  ...                     71898
10                           637    9  ...                      3070

   Supported Housing Social Rent              General Needs Affordable Rent  \
                             PRP   LA2  Total                           PRP
0                           6149   259   6408                          1893
1                           1304    73   1377                          5101
2                           9914   391  10305                          1996
3                             48    15     63                           315
4                            222    59    281                           669
5                            142    19    161                          2586
6                           6701  1678   8379                           609
7                            943   314   1257                           196
8                            635    95    730                          1385
9                          26058  2903  28961                         14750
10                          2386    38   2424                           811

                Supported Housing Affordable Rent
      LA  Total                               PRP   LA Total
0    174   2067                               362   16   378
1    364   5465                                73    0    73
2    150   2146                               456    8   464
3     29    344                                 3    0     3
4     66    735                                 8    2    10
5    199   2785                                11    0    11
6    122    731                               439   97   536
7     29    225                                99   12   111
8     79   1464                                47    2    49
9   1212  15962                              1498  137  1635
10    18    829                               116    1   117

[11 rows x 28 columns]

In [291]:
df3a2a = createDF(sheet='Table 3a', skipRows=33, skipFooter=30, header=[0,1])
# display(df3a2a)

In [292]:
df3a2b = createDF(sheet='Table 3a', skipRows=47, skipFooter=15, header=[0,1])
# display(df3a2b)

In [311]:
df3a2 = pd.merge(df3a2a, df3a2b, how="inner", left_index=True, right_index=True)
# display(df3a2)

In [318]:
df3a = pd.concat([df3a1, df3a2], axis=1)
# display(df3a)

# Table 3b: Economic status of lead tenant3 by type of letting, for new social housing lettings, 2019/20 to 2020/21 April to September

In [327]:
df3b1a = createDF(sheet='Table 3b', skipRows=4, skipFooter=57, header=[0,1])
# display(df3b1a)

In [328]:
df3b1b = createDF(sheet='Table 3b', skipRows=18, skipFooter=44, header=[0,1])
# display(df3b1b)

In [331]:
df3b1 = pd.merge(df3b1a, df3b1b, how="inner", left_index=True, right_index=True)
# display(df3b1)

In [333]:
df3b2a = createDF(sheet='Table 3b', skipRows=32, skipFooter=30, header=[0,1])
# display(df3b2a)

In [334]:
df3b2b = createDF(sheet='Table 3b', skipRows=46, skipFooter=14, header=[0,1])
# display(df3b2b)

In [335]:
df3b2 = pd.merge(df3b2a, df3b2b, how="inner", left_index=True, right_index=True)
df3b = pd.merge(df3b1, df3b2, how="inner", left_index=True, right_index=True)
display(df3b)

       2020/21 April to September All Lettings_x_x  \

0                Full time worker            13329
1               Part time worker1             7037
2                     All workers            20366
3          Unemployed (Jobseeker)            11839
4                         Retired             7678
5                Not seeking work            15418
6  Unable to work due to sickness            11517
7                          Other2             2499
8                           Total            69317

  General Needs Social Rent_x_x                \
                            PRP     LA  Total
0                          7575   2253   9828
1                          3645   1223   4868
2                         11220   3476  14696
3                          4479   2243   6722
4                          2282   1005   3287
5                          7117   2864   9981
6                          4529   1998   6527
7                           735    612   1347
8                         30362  12198  42560

  Supported Housing Social Rent_x_x               \
                                PRP    LA  Total
0                               642   140    782
1                               497    99    596
2                              1139   239   1378
3                              3814   132   3946
4                              2880   817   3697
5                              2994   175   3169
6                              3392   375   3767
7                               840    28    868
8                             15059  1766  16825

  General Needs Affordable Rent_x_x       ... General Needs Social Rent_y_y  \
                                PRP   LA  ...                         Total
0                              2374  143  ...                      0.258974
1                              1462   73  ...                      0.134489
2                              3836  216  ...                      0.393464
3                               920   99  ...                      0.139010
4                               357   64  ...                      0.079086
5                              2014  108  ...                      0.199423
6                               954   93  ...                      0.159693
7                               218   32  ...                      0.029324
8                              8299  612  ...                      1.000000

  Supported Housing Social Rent_y_y                      \
                                PRP        LA     Total
0                          0.043182  0.078699  0.046811
1                          0.035143  0.040923  0.035733
2                          0.078325  0.119622  0.082544
3                          0.231473  0.065757  0.214544
4                          0.236966  0.501574  0.263999
5                          0.151278  0.073102  0.143291
6                          0.243493  0.222106  0.241308
7                          0.058465  0.017838  0.054315
8                          1.000000  1.000000  1.000000

  General Needs Affordable Rent_y_y                      \
                                PRP        LA     Total
0                          0.297648  0.205085  0.290529
1                          0.187840  0.167797  0.186298
2                          0.485488  0.372881  0.476827
3                          0.098792  0.134746  0.101558
4                          0.036438  0.080508  0.039828
5                          0.219688  0.217797  0.219542
6                          0.127886  0.178814  0.131804
7                          0.031707  0.015254  0.030441
8                          1.000000  1.000000  1.000000

  Supported Housing Affordable Rent_y_y
                                    PRP        LA     Total
0                              0.037679  0.051095  0.038934
1                              0.042200  0.029197  0.040984
2                              0.079879  0.080292  0.079918
3                              0.153730  0.043796  0.143443
4                              0.342125  0.664234  0.372268
5                              0.146948  0.036496  0.136612
6                              0.241899  0.167883  0.234973
7                              0.035418  0.007299  0.032787
8                              1.000000  1.000000  1.000000

[9 rows x 56 columns]

# Table 3c: Previous housing situation of lead tenant3, for new social housing lettings, 2019/20 to 2020/21 April to September

In [352]:
df3c1a = createDF(sheet='Table 3c', skipRows=5, skipFooter=50, header=[0])
df3c1a = df3c1a.rename(columns={'PRP': 'GN SR PRP', 'LA': 'GN SR LA', 'Total': 'All GN SR', 'PRP': 'SH SR PRP', 'LA.1' : 'SH SR LA',
'Total.1': 'All SH SR', 'PRP.2': 'GN AR PRP', 'LA.2': 'GN AR LA', 'Total.2': 'All GN AR', 'PRP.3': 'SH AR PRP', 'LA.3': 'SH AR LA', 'Total.3': 'All SH AR'})

# display(df3c1a)

In [349]:
df3c1b = createDF(sheet='Table 3c', skipRows=16, skipFooter=39, header=0)
# display(df3c1b)

In [347]:
df3c1 = pd.merge(df3c1a, df3c1b, how="inner", left_index=True, right_index=True)
display(df3c1)

,"(,)","(,)","(SH SR PRP,)","(GN SR LA,)","(All GN SR,)","(PRP.1,)","(SH SR LA,)","(All SH SR,)","(GN AR PRP,)","(GN AR LA,)",...,All GN SR,SH SR PRP,SH SR LA,All SH SR,GN AR PRP,GN AR LA,All GN AR,SH AR PRP,SH AR LA,All SH AR
0,General Needs social tenancy,17690,8475,3874,12349,1654,486,2140,2856,222,...,0.266971,0.095734,0.262561,0.111878,0.309627,0.333835,0.311255,0.121179,0.255319,0.127726
1,Supported housing,4601,1318,556,1874,2197,85,2282,255,25,...,0.040514,0.127163,0.045921,0.119302,0.027645,0.037594,0.028314,0.176856,0.063830,0.171340
2,Owner occupation (private or shared ownership),1544,487,206,693,616,65,681,119,5,...,0.014982,0.035654,0.035116,0.035602,0.012901,0.007519,0.012539,0.041485,0.170213,0.047767
3,Private sector tenancy,11908,6017,2045,8062,1557,362,1919,1704,91,...,0.174291,0.090120,0.195570,0.100324,0.184735,0.136842,0.181515,0.133188,0.212766,0.137072
4,Living with family / friends,17506,8314,2497,10811,3933,336,4269,2143,102,...,0.233721,0.227644,0.181524,0.223181,0.232329,0.153383,0.227020,0.193231,0.085106,0.187954
5,Temporary accommodation1,11998,4584,2396,6980,3290,197,3487,1258,131,...,0.150899,0.190427,0.106429,0.182298,0.136383,0.196992,0.140459,0.149563,0.106383,0.147456
6,Other2,10989,3763,1724,5487,4030,320,4350,889,89,...,0.118622,0.233258,0.172880,0.227415,0.096379,0.133835,0.098898,0.184498,0.106383,0.180685
7,Total,76236,32958,13298,46256,17277,1851,19128,9224,665,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [354]:
df3c2a = createDF(sheet='Table 3c', skipRows=28, skipFooter=26, header=0)
df3c2a = df3c2a.rename(columns={'PRP': 'GN SR PRP', 'LA': 'GN SR LA', 'Total': 'All GN SR', 'PRP': 'SH SR PRP', 'LA.1' : 'SH SR LA',
'Total.1': 'All SH SR', 'PRP.2': 'GN AR PRP', 'LA.2': 'GN AR LA', 'Total.2': 'All GN AR', 'PRP.3': 'SH AR PRP', 'LA.3': 'SH AR LA', 'Total.3': 'All SH AR'})
# display(df3c2a)

In [355]:
df3c2b = createDF(sheet='Table 3c', skipRows=40, skipFooter=15, header=0)
# display(df3c2b)

In [357]:
df3c2 = pd.merge(df3c2a, df3c2b, how="inner", left_index=True, right_index=True)
df3c = pd.merge(df3c1, df3c2, how="inner", left_index=True, right_index=True)
display(df3c)

,"(,)","(,)","(SH SR PRP,)","(GN SR LA,)","(All GN SR,)","(PRP.1,)","(SH SR LA,)","(All SH SR,)","(GN AR PRP,)","(GN AR LA,)",...,All GN SR_y,SH SR PRP_y,SH SR LA_y,All SH SR_y,GN AR PRP_y,GN AR LA_y,All GN AR_y,SH AR PRP_y,SH AR LA_y,All SH AR_y
0,General Needs social tenancy,17690,8475,3874,12349,1654,486,2140,2856,222,...,0.382030,0.154022,0.374362,0.174669,0.396119,0.359350,0.393425,0.204461,0.384058,0.218607
1,Supported housing,4601,1318,556,1874,2197,85,2282,255,25,...,0.035455,0.129061,0.059504,0.122543,0.029111,0.038211,0.029778,0.168525,0.094203,0.162671
2,Owner occupation (private or shared ownership),1544,487,206,693,616,65,681,119,5,...,0.015980,0.035157,0.056783,0.037183,0.014202,0.017073,0.014412,0.048947,0.094203,0.052511
3,Private sector tenancy,11908,6017,2045,8062,1557,362,1919,1704,91,...,0.160095,0.083708,0.164570,0.091286,0.177624,0.198374,0.179144,0.074349,0.159420,0.081050
4,Living with family / friends,17506,8314,2497,10811,3933,336,4269,2143,102,...,0.217333,0.197757,0.144849,0.192799,0.207442,0.217886,0.208207,0.177819,0.094203,0.171233
5,Temporary accommodation1,11998,4584,2396,6980,3290,197,3487,1258,131,...,0.105245,0.135178,0.090445,0.130986,0.103142,0.109756,0.103627,0.118959,0.057971,0.114155
6,Other2,10989,3763,1724,5487,4030,320,4350,889,89,...,0.083862,0.265117,0.109487,0.250534,0.072360,0.059350,0.071407,0.206939,0.115942,0.199772
7,Total,76236,32958,13298,46256,17277,1851,19128,9224,665,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# Table 3d: Other household characteristics of new social housing lettings, 2019/20 to 2020/21 April to September

In [358]:
df3d1 = createDF(sheet='Table 3d', skipRows=4, skipFooter=19, header=[0,1])
# display(df3d1)

In [359]:
df3d2 = createDF(sheet='Table 3d', skipRows=18, skipFooter=16, header=[0,1])
# display(df3d2)

In [360]:
df3d = pd.merge(df3d1, df3d2, how="inner", left_index=True, right_index=True)
display(df3d)

                          2020/21 April to September  \
                   % of lettings with characteristic
0                              Statutorily homeless1
1                             New to social housing2
2  Household left last settled home because of ov...
3  Household left last settled home because of un...
4                            New to Local Authority5
5                       Given Reasonable Preference6
7  Don't Know7 - Household’s reason for leaving l...
8                Don't Know7 - Reasonable Preference

                     All Lettings_x General Needs Social Rent_x            \
  % of lettings with characteristic                         PRP        LA
0                          0.213928                    0.188664  0.260641
1                          0.680886                     0.69003  0.645887
2                          0.112462                    0.141225  0.118037
3                          0.021911                    0.023354  0.034023
4                          0.141377                    0.145428  0.058129
5                          0.442846                    0.400612  0.628298
7                          0.115195                    0.089265  0.171154
8                          0.264888                    0.226864   0.20755

            Supported Housing Social Rent_x                      \
      Total                             PRP        LA     Total
0  0.209357                        0.236847  0.243112  0.237453
1  0.677339                        0.716907  0.603998  0.705981
2  0.134997                        0.011878  0.012407  0.011929
3   0.02622                        0.007407   0.05397  0.011929
4   0.12033                        0.214389  0.092382  0.202583
5  0.467226                        0.352618  0.586018  0.380988
7  0.112807                        0.132604  0.129119  0.132267
8  0.221312                        0.389709  0.211777  0.372491

  General Needs Affordable Rent_x            ... General Needs Social Rent_y  \
                              PRP        LA  ...                       Total
0                        0.188096   0.21203  ...                    0.156974
1                        0.654055  0.619549  ...                    0.575939
2                        0.204342  0.202091  ...                    0.150825
3                        0.020995  0.029617  ...                    0.033659
4                        0.116435   0.04812  ...                    0.111207
5                        0.426018  0.531191  ...                    0.431150
7                        0.091175  0.136842  ...                    0.111021
8                        0.259974  0.204511  ...                    0.238795

  Supported Housing Social Rent_y                      \
                              PRP        LA     Total
0                        0.193292  0.192792  0.193245
1                        0.664534  0.529412  0.651872
2                        0.015883  0.011597  0.015461
3                        0.008924  0.045267  0.012509
4                        0.220433  0.094526  0.208635
5                        0.312476  0.543561  0.339177
7                        0.140487  0.089085  0.135670
8                        0.366791  0.199932  0.351155

  General Needs Affordable Rent_y                      \
                              PRP        LA     Total
0                        0.150119  0.183740  0.152582
1                        0.570850  0.586992  0.572033
2                        0.204456  0.136324  0.199400
3                        0.025310  0.049252  0.027087
4                        0.122229  0.074797  0.118754
5                        0.400639  0.524125  0.412100
7                        0.087334  0.074797  0.086415
8                        0.336097  0.140650  0.321780

  Supported Housing Affordable Rent_y
                                  PRP        LA     Total
0                            0.184634  0.072464  0.175799
1                            0.586741  0.442029  0.575342
2                            0.009296  0.000000  0.008557
3                            0.003320  0.030769  0.005501
4                            0.210657  0.115942  0.203196
5                            0.304695  0.484615  0.325376
7                            0.066914  0.050725  0.065639
8                            0.379802  0.057971  0.354452

[8 rows x 28 columns]

# Table 3e: Reason the household left their last settled home, for new social housing lettings, 2019/20 to 2020/21 April to September

In [364]:
df3e1 = createDF(sheet='Table 3e', skipRows=4, skipFooter=50, header=[0,1])
# display(df3e1)

In [365]:
df3e2 = createDF(sheet='Table 3e', skipRows=42, skipFooter=10, header=[0,1])
# display(df3e2)

In [366]:
df3e = pd.merge(df3e1, df3e2, how="inner", left_index=True, right_index=True)
display(df3e)

                           2020/21 April to September All Lettings_x  \
                                        % of lettings  % of lettings
0   Permanently decanted from another property own...       0.008969
1                        Left home country as refugee       0.006731
2   Discharged from prison/longstay hospital/other...       0.013120
3                          Loss of tied accommodation       0.008421
4                                      Domestic abuse       0.071471
5   (Non-violent) relationship breakdown with partner       0.055104
6                 Asked to leave by family or friends       0.117932
7                                   Racial harassment       0.001171
8                      Other problems with neighbours       0.031622
9         Property unsuitable because of overcrowding       0.112462
10  Property unsuitable because of ill health/disa...       0.105257
11      Property unsuitable because of poor condition       0.024016
12            To move nearer to family/friends/school       0.045275
13                                To move nearer work       0.006286
14              To move to accommodation with support       0.071471
15               To move to independent accommodation       0.136271
16                                              Other       0.064755
17   Under occupation - offered incentive to downsize       0.007264
18                    Under occupation - no incentive       0.014647
19                                         Hate crime       0.001912
20  End of Assured shorthold tenancy or Fixed term...       0.000000
21  End of Assured shorthold tenancy or Fixed term...       0.000000
22                                       Repossession       0.002431
23  Couldn't afford fees attached to renewing the ...       0.000771
24               Couldn't afford the increase in rent       0.006716
25  Couldn't afford rent or mortgage -welfare reforms       0.001823
26        Couldn't afford rent or mortgage-employment       0.003929
27             Couldn't afford rent or mortgage-other       0.008865
28  End of Assured shorthold tenancy -  on a ‘no f...       0.034112
29  End of Assured shorthold tenancy - eviction; t...       0.003958
30  End of Fixed Term tenancy -  on a ‘no fault’ b...       0.031192
31  End of Fixed Term tenancy - eviction; tenant a...       0.002046
32                              Missing / Don't know1       0.115195

   General Needs Social Rent_x                      \
                           PRP        LA     Total
0                     0.009728  0.012248  0.010405
1                     0.005064  0.012158  0.006969
2                     0.004664  0.006623  0.005190
3                     0.007696  0.009799  0.008261
4                     0.059402  0.075304  0.063673
5                     0.057936  0.054255  0.056947
6                     0.100646  0.122754  0.106584
7                     0.001566  0.001089  0.001438
8                     0.037480  0.035837  0.037039
9                     0.141225  0.118037  0.134997
10                    0.101313  0.127563  0.108363
11                    0.027619  0.025676  0.027097
12                    0.052239  0.035202  0.047663
13                    0.008695  0.003901  0.007408
14                    0.009128  0.016150  0.011014
15                    0.184668  0.154328  0.176519
16                    0.061434  0.053711  0.059360
17                    0.005897  0.016422  0.008724
18                    0.017457  0.017601  0.017496
19                    0.002465  0.002087  0.002364
20                    0.000000  0.000000  0.000000
21                    0.000000  0.000000  0.000000
22                    0.002499  0.002994  0.002632
23                    0.000700  0.001361  0.000877
24                    0.008595  0.006351  0.007993
25                    0.001999  0.002631  0.002169
26                    0.004098  0.004083  0.004094
27                    0.010694  0.008528  0.010113
28                    0.037846  0.042007  0.038964
29                    0.002632  0.003901  0.002973
30                    0.033549  0.025767  0.031459
31                    0.001066  0.001633  0.001218
32                    0.089265  0.171154  0.112807

   Supported Housing Social Rent_x                      \
                               PRP        LA     Total
0                         0.006339  0.012407  0.006929
1                         0.008208  0.001241  0.007531
2                         0.040171  0.008685  0.037113
3                         0.007674  0.014268  0.008314
4                         0.098759  0.035360  0.092602
5                         0.050380  0.040323  0.049404
6                         0.162285  0.125931  0.158754
7                         0.000467  0.000620  0.000482
8                         0.020419  0.032878  0.021629
9                         0.011878  0.012407  0.011929
10                        0.099827  0.254963  0.114893
11                        0.014080  0.019231  0.014580
12                        0.037435  0.078784  0.041451
13                        0.002202  0.001241  0.002109
14                        0.256239  0.116625  0.242680
15                        0.045442  0.055831  0.046451
16                        0.079474  0.062035  0.077780
17                        0.002135  0.035360  0.005362
18                        0.005272  0.018610  0.006567
19                        0.000934  0.001861  0.001024
20                        0.000000  0.000000  0.000000
21                        0.000000  0.000000  0.000000
22                        0.002269  0.004342  0.002470
23                        0.000601  0.001861  0.000723
24                        0.002736  0.008065  0.003253
25                        0.001001  0.002481  0.001145
26                        0.003737  0.001861  0.003555
27                        0.006072  0.008065  0.006266
28                        0.015214  0.030397  0.016689
29                        0.007407  0.001861  0.006868
30                        0.006539  0.012407  0.007109
31                        0.004804  0.000000  0.004338
32                        0.132604  0.129119  0.132267

   General Needs Affordable Rent_x            ... General Needs Social Rent_y  \
                               PRP        LA  ...                       Total
0                         0.006680  0.006969  ...                    0.015800
1                         0.004533  0.000000  ...                    0.009108
2                         0.002863  0.005226  ...                    0.004561
3                         0.008827  0.020906  ...                    0.007848
4                         0.062388  0.062718  ...                    0.046365
5                         0.060837  0.041812  ...                    0.054018
6                         0.093880  0.108014  ...                    0.093225
7                         0.001312  0.001742  ...                    0.001035
8                         0.026959  0.029617  ...                    0.034661
9                         0.204342  0.202091  ...                    0.150544
10                        0.066563  0.080139  ...                    0.105994
11                        0.028749  0.027875  ...                    0.029124
12                        0.042348  0.027875  ...                    0.049936
13                        0.009901  0.003484  ...                    0.009348
14                        0.004533  0.090592  ...                    0.008613
15                        0.128474  0.118467  ...                    0.166344
16                        0.069068  0.040070  ...                    0.059029
17                        0.003698  0.020906  ...                    0.010713
18                        0.017297  0.008711  ...                    0.022882
19                        0.001551  0.001742  ...                    0.002086
20                        0.000000  0.000000  ...                    0.000000
21                        0.000000  0.000000  ...                    0.000000
22                        0.001312  0.005226  ...                    0.004066
23                        0.000477  0.000000  ...                    0.001215
24                        0.007754  0.008711  ...                    0.009228
25                        0.001670  0.001742  ...                    0.004306
26                        0.003937  0.005226  ...                    0.005087
27                        0.008827  0.005226  ...                    0.011944
28                        0.047000  0.040070  ...                    0.044204
29                        0.002505  0.003484  ...                    0.003166
30                        0.080043  0.027875  ...                    0.032020
31                        0.001670  0.003484  ...                    0.001666
32                        0.091175  0.136842  ...                    0.001861

   Supported Housing Social Rent_y                      \
                               PRP        LA     Total
0                         0.013989  0.034341  0.015999
1                         0.012066  0.002613  0.011133
2                         0.038981  0.017171  0.036827
3                         0.006217  0.016797  0.007262
4                         0.093464  0.030608  0.087256
5                         0.049861  0.041060  0.048992
6                         0.139030  0.082120  0.133410
7                         0.000900  0.001120  0.000922
8                         0.019920  0.027996  0.020717
9                         0.015870  0.011571  0.015446
10                        0.107003  0.282195  0.124304
11                        0.013212  0.024263  0.014303
12                        0.048102  0.065323  0.049803
13                        0.002004  0.002240  0.002028
14                        0.257690  0.144084  0.246470
15                        0.043235  0.042553  0.043167
16                        0.059187  0.032475  0.056549
17                        0.001800  0.023890  0.003981
18                        0.007117  0.021277  0.008516
19                        0.001268  0.000747  0.001217
20                        0.000000  0.000000  0.000000
21                        0.000000  0.000000  0.000000
22                        0.004949  0.004853  0.004940
23                        0.000736  0.000747  0.000737
24                        0.003845  0.007465  0.004202
25                        0.001963  0.003359  0.002101
26                        0.002618  0.003359  0.002691
27                        0.007444  0.007465  0.007446
28                        0.019061  0.041060  0.021233
29                        0.012312  0.006346  0.011723
30                        0.008958  0.013811  0.009437
31                        0.006381  0.004853  0.006230
32                        0.000818  0.002240  0.000958

   General Needs Affordable Rent_y                      \
                               PRP        LA     Total
0                         0.007464  0.004394  0.007236
1                         0.006619  0.006151  0.006584
2                         0.002676  0.001757  0.002608
3                         0.006619  0.005272  0.006519
4                         0.044149  0.052724  0.044785
5                         0.052105  0.044815  0.051565
6                         0.085692  0.073814  0.084811
7                         0.001549  0.000879  0.001499
8                         0.026193  0.044815  0.027575
9                         0.204197  0.136204  0.199153
10                        0.063371  0.110721  0.066884
11                        0.031897  0.025483  0.031421
12                        0.042670  0.056239  0.043677
13                        0.008309  0.009666  0.008409
14                        0.004506  0.007030  0.004694
15                        0.140966  0.180141  0.143872
16                        0.085833  0.050088  0.083181
17                        0.005563  0.015817  0.006323
18                        0.019716  0.033392  0.020730
19                        0.002042  0.003515  0.002151
20                        0.000000  0.000000  0.000000
21                        0.000000  0.000000  0.000000
22                        0.003661  0.004394  0.003716
23                        0.001197  0.000000  0.001108
24                        0.010703  0.010545  0.010691
25                        0.003732  0.004394  0.003781
26                        0.004999  0.007030  0.005150
27                        0.012674  0.018453  0.013103
28                        0.049923  0.049209  0.049870
29                        0.002817  0.003515  0.002868
30                        0.065272  0.034271  0.062973
31                        0.001619  0.004394  0.001825
32                        0.001267  0.000879  0.001239

   Supported Housing Affordable Rent_y
                                   PRP        LA     Total
0                             0.010624  0.076336  0.015883
1                             0.002656  0.000000  0.002443
2                             0.035857  0.007634  0.033598
3                             0.007304  0.000000  0.006720
4                             0.098274  0.007634  0.091020
5                             0.021912  0.015267  0.021381
6                             0.082337  0.045802  0.079414
7                             0.000000  0.000000  0.000000
8                             0.015936  0.061069  0.019548
9                             0.009296  0.000000  0.008552
10                            0.136122  0.412214  0.158216
11                            0.008632  0.030534  0.010385
12                            0.035857  0.076336  0.039096
13                            0.001992  0.000000  0.001833
14                            0.395086  0.091603  0.370800
15                            0.041833  0.083969  0.045205
16                            0.032537  0.015267  0.031155
17                            0.000000  0.007634  0.000611
18                            0.003320  0.022901  0.004887
19                            0.000000  0.007634  0.000611
20                            0.000000  0.000000  0.000000
21                            0.000000  0.000000  0.000000
22                            0.001992  0.007634  0.002443
23                            0.000664  0.000000  0.000611
24                            0.000664  0.007634  0.001222
25                            0.000000  0.000000  0.000000
26                            0.001328  0.007634  0.001833
27                            0.002656  0.000000  0.002443
28                            0.021912  0.007634  0.020770
29                            0.017264  0.000000  0.015883
30                            0.011952  0.000000  0.010996
31                            0.001992  0.000000  0.001833
32                            0.000000  0.007634  0.000611

[33 rows x 28 columns]

# Table 4a: Analysis of 2019/20 dataset submission rates to indicate data quality of 2020/21 dataset

In [98]:
df4a = createDF(sheet='Table 4a', skipRows=5, skipFooter=12, header=0)
display(df4a)

,Unnamed: 0,19/20 submitted by 8 Feb 2020,19/20 submitted by \nyear end (unweighted),19/20 submitted by year end (weighted),Submitted by 8 Feb as % of submitted by year end,Submitted by 8 Feb as % of weighted final total,% of final total accounted \nfor by weighting
0,April,22829.0,26584.0,28853.722869,0.858750,0.791198,0.078663
1,May,20508.0,23652.0,25917.158652,0.867073,0.791290,0.087400
2,June,19809.0,23123.0,25354.452989,0.856679,0.781283,0.088010
3,July,22932.0,26919.0,29584.368267,0.851889,0.775139,0.090094
4,August,18847.0,22854.0,25045.251002,0.824670,0.752518,0.087492
5,September,20224.0,24760.0,27268.399744,0.816801,0.741664,0.091989
6,April to September,125149.0,147892.0,162023.353523,0.846219,0.772413,0.087218

# Table 4b: Proportion of new lettings where demographic questions refused

In [101]:
df4b = createDF(sheet='Table 4b', skipRows=5, skipFooter=12, header=0)
display(df4b)

,Unnamed: 0,2020/21 submitted by 8 Feb,2019/20 submitted by 8 Feb,2019/20 submitted by year end,2018/19 submitted by year end
0,Age of lead tenant,0.052996,0.046772,0.042049,0.042438
1,Gender of lead tenant,0.052905,0.045332,0.035782,0.039791
2,Economic status of lead tenant,0.093398,0.089070,0.087675,0.090242
3,Nationality of lead tenant,0.085276,0.071294,0.077897,0.083763
4,Ethnicity of lead tenant,0.089775,0.077743,0.077302,0.076524
5,Household income,0.518612,0.546228,0.481477,0.488482